# Generated by Django 4.1.3 on 2024-02-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Automobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100, null=True)),
                ("store_name", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
                ("lat", models.CharField(max_length=30, null=True)),
                ("lon", models.CharField(max_length=30, null=True)),
                ("pincode", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Electronic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50, null=True)),
                ("store_name", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=600, null=True)),
                ("phone", models.CharField(max_length=300, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
                ("lat", models.CharField(max_length=30, null=True)),
                ("lon", models.CharField(max_length=30, null=True)),
                ("pincode", models.CharField(max_length=20, null=True)),
                ("type", models.CharField(max_length=50, null=True)),
                ("operating_time", models.CharField(max_length=400, null=True)),
                ("brand_logo", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entertainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
                ("store_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("lat", models.CharField(max_length=30)),
                ("lon", models.CharField(max_length=30)),
                ("pincode", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Supermarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=30)),
                ("store_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=30)),
                ("lon", models.CharField(max_length=30)),
                ("pincode", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Telecom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100, null=True)),
                ("store_name", models.CharField(max_length=300, null=True)),
                ("address", models.CharField(max_length=400, null=True)),
                ("phone", models.CharField(max_length=15, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
                ("lat", models.CharField(max_length=30, null=True)),
                ("lon", models.CharField(max_length=30, null=True)),
                ("pincode", models.CharField(max_length=10, null=True)),
                ("store_type", models.CharField(max_length=250, null=True)),
                ("operating_time", models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
