# Generated by Django 4.0.3 on 2024-02-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorwalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='store_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
