# Generated by Django 4.1.3 on 2024-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("floorwalk", "0002_alter_automobile_store_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobile",
            name="store_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
