# Generated by Django 4.0.3 on 2024-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorwalk', '0003_alter_automobile_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nothing', models.CharField(max_length=10, null=True)),
                ('something', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
