# Generated by Django 4.0.3 on 2024-02-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorwalk', '0004_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
